ALTER TABLE orders
ADD COLUMN delivery_partner VARCHAR(255) DEFAULT NULL,
ADD COLUMN tracking_number VARCHAR(255) DEFAULT NULL,
ADD COLUMN tracking_status VARCHAR(255) DEFAULT NULL,
ADD COLUMN tracking_last_updated TIMESTAMP NULL DEFAULT NULL;
