CREATE TABLE IF NOT EXISTS section_presets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(100) NOT NULL,
    category VARCHAR(100) DEFAULT NULL,
    section_json TEXT NOT NULL,
    created_by INT DEFAULT NULL,
    is_shared TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
