CREATE TABLE IF NOT EXISTS page_templates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    layout_json TEXT NOT NULL,
    preview_image VARCHAR(255) DEFAULT NULL,
    tags VARCHAR(255) DEFAULT NULL,
    created_by INT DEFAULT NULL,
    is_shared TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
