CREATE TABLE IF NOT EXISTS global_sections (
  id INT AUTO_INCREMENT PRIMARY KEY,
  handle VARCHAR(255) NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL,
  type VARCHAR(100) NOT NULL,
  section_json TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
